import "./css/style.css";

import { Inter, Architects_Daughter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import Header from "@/components/ui/header";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const architects_daughter = Architects_Daughter({
  subsets: ["latin"],
  variable: "--font-architects-daughter",
  weight: "400",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${architects_daughter.variable} font-inter antialiased bg-athenix-white text-gray-200 tracking-tight bg-athenix-white`}
      >
        <div className="flex flex-col min-h-screen overflow-hidden">
          <Header />
          {children}
          <Analytics />
        </div>
        <script
          type="text/javascript"
          src="../../node_modules/tw-elements/js/tw-elements.umd.min.js"
        ></script>
      </body>
    </html>
  );
}
